contacts/urls.py
from django.urls import path

from contacts import views

app_name = "contacts"

urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    # contact
    path("contact/<int:contact_id>/detail/", views.contact, name="contact"),
    path("contact/create/", views.create, name="create"),
    # path("contact/<int:contact_id>/update/", views.contact, name="contact"),
    # path("contact/<int:contact_id>/delete/", views.contact, name="contact"),
]

core/urls.py
# from django.conf import settings
# from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("contacts.urls")),
    path("admin/", admin.site.urls),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # noqa

contacts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=20)
    email = models.EmailField(max_length=150)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True, null=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(
        upload_to='pictures/%Y/%m/', blank=True, null=True
    )
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, blank=True, null=True
    )
    owner = models.ForeignKey(
        User, on_delete=models.SET_NULL, blank=True, null=True
    )

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

contacts/views.py
from django.shortcuts import render


def index(request):
    return render(request, "contacts/index.html")

contacts/views/contact_forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.shortcuts import render

from contacts.models import Contact


class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = (
            "first_name",
            "last_name",
            "email",
            "phone",
            "description",
        )

    def clean(self):
        self.add_error(
            "first_name",
            ValidationError("First name is required", code="required"),
        )

        return super().clean()


def create(request):
    if request.method == "POST":
        context = {
            "form": ContactForm(data=request.POST or None),
        }

        return render(request, "contacts/create.html", context)

    context = {
        "form": ContactForm(),
    }

    return render(request, "contacts/create.html", context)

contacts/views/contact_view.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render

from contacts.models import Contact


def index(request):
    contacts = Contact.objects.filter(show=True).order_by("-id")
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {"page_obj": page_obj}

    return render(request, "contacts/index.html", context)


def contact(request, contact_id):
    # single_contact = Contact.objects.filter(pk=contact_id).first()
    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)
    context = {"contact": single_contact}

    return render(request, "contacts/contact.html", context)


def search(request):
    query = request.GET.get("q", "").strip()

    if query == "" or len(query) <= 0:
        return redirect("contacts:index")

    contacts = (
        Contact.objects.filter(
            Q(first_name__icontains=query)
            | Q(last_name__icontains=query)
            | Q(email__icontains=query)
            | Q(phone__icontains=query)
        )
        .filter(show=True)
        .order_by("-id")
    )

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {"page_obj": page_obj}

    return render(request, "contacts/index.html", context)

contacts/views/contact_views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render

from contacts.models import Contact


def index(request):
    contacts = Contact.objects.filter(show=True).order_by("-id")
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {"page_obj": page_obj}

    return render(request, "contacts/index.html", context)


def contact(request, contact_id):
    # single_contact = Contact.objects.filter(pk=contact_id).first()
    single_contact = get_object_or_404(Contact, pk=contact_id, show=True)
    context = {"contact": single_contact}

    return render(request, "contacts/contact.html", context)


def search(request):
    query = request.GET.get("q", "").strip()

    if query == "" or len(query) <= 0:
        return redirect("contacts:index")

    contacts = (
        Contact.objects.filter(
            Q(first_name__icontains=query)
            | Q(last_name__icontains=query)
            | Q(email__icontains=query)
            | Q(phone__icontains=query)
        )
        .filter(show=True)
        .order_by("-id")
    )

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {"page_obj": page_obj}

    return render(request, "contacts/index.html", context)

contacts/templates/contacts/contact.html
{% extends 'global/base.html' %}
{% load static %}

{% block 'head' %}
  <link rel="stylesheet" href="{% static 'contacts/css/styles.css' %}" />
{% endblock %}

{% block 'title' %} Agenda - {{ contact.first_name }} {% endblock %}

{% block 'content' %}
  <section class="single-contact">
    <h1>
      {{ contact.first_name }} {{ contact.last_name }}
    </h1>
    <p>
      <strong>ID:</strong> {{ contact.id }}
    </p>
    <p>
      <strong>Phone:</strong> {{ contact.phone }}
    </p>
    <p>
      <strong>E-mail:</strong> {{ contact.email }}
    </p>
    <p>
      <strong>Created Date:</strong> {{ contact.created_date }}
    </p>
    <p>
      <strong>Category:</strong> {{ contact.category.name }}
    </p>
    <p>
      <strong>Description:</strong> {{ contact.description }}
    </p>
  </section>
{% endblock %}

contacts/templates/contacts/create.html
{% extends 'global/base.html' %}
{% load static %}

{% block 'head' %}
  <link rel="stylesheet" href="{% static 'contacts/css/styles.css' %}">
{% endblock  %}

{% block 'title' %} Criando contato {% endblock  %}

{% block 'content' %}
  <section class="form-wrapper">

    <h2>Contact</h2>

    <form 
      action="{% url 'contacts:create' %}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <div class="form-content">  
        {% for field in form %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            {{ field.errors }}
          </div>
        {% endfor %}
      </div>
      
      {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}
        
      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>
    </form>
  </section>
{% endblock %}

contacts/templates/contacts/index.html
{% extends 'global/base.html' %}
{% load static %}

{% block 'head' %}
  <link rel="stylesheet" href="{% static 'contacts/css/styles.css' %}">
{% endblock %}

{% block 'title' %} Agenda {% endblock %}

{% block 'content' %}
{% if page_obj %}
  <div class="responsive-table">
    <table class="contacts-table">
      <caption class="table-caption">
        Contacts
      </caption>
      <thead>
        <tr class="table-row table-row-header">
          <th class="table-header">Id</th>
          <th class="table-header">First Name</th>
          <th class="table-header">Last Name</th>
          <th class="table-header">Phone</th>
          <th class="table-header">E-mail</th>
        </tr>
      </thead>
      <tbody>
        {% for contact in page_obj %}
          <tr class="table-row">
            <td class="table-cel">
              <a 
                href="{% url 'contacts:contact' contact.id %}"
                class="table-link"
              >
                {{ contact.id }}
              </a>
            </td>
            <td class="table-cel">{{ contact.first_name }}</td>
            <td class="table-cel">{{ contact.last_name }}</td>
            <td class="table-cel">{{ contact.phone }}</td>
            <td class="table-cel">{{ contact.email }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% else %}
  <section class="single-contact">
    <h1>
      Nenhum contato encontrado
    </h1>
  </section>
{% endif %}
{% endblock  %}

templates/global/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block 'head' %}{% endblock %}
  <link rel="shortcut icon" href="{% static 'global/imgs/favicon.ico' %}" type="image/x-icon">
  <link rel="stylesheet" href="{% static 'global/css/styles.css' %}">
  <title>{% block 'title' %}{% endblock %}</title>
</head>
<body>
  {% include 'global/header.html' %}
  <main class="content">
    {% block 'content' %}{% endblock %}
    {% include 'global/paginator.html' %}
  </main>
</body>
</html>

templates/global/header.html
<header class="header">
  <h1 class="header-heading">
    <a href="{% url 'contacts:index' %}" class="header-link">
      Agenda
    </a>
  </h1>

  <nav class="menu">
    <ul class="menu-list">
      <li class="menu-item">
        <a href="" class="menu-link">
          Link
        </a>
      </li>
      <li class="menu-item">
        <a href="" class="menu-link">
          Link
        </a>
      </li>
    </ul>
  </nav>

  <section class="search">
    <form action="{% url 'contacts:search' %}" method="GET">
      <input 
        type="search" 
        class="search-input"
        placeholder="Pesquisar"
        id="search"
        name="q"
        value="{{ request.GET.q.strip }}"
      >
    </form>
  </section>
</header>

templates/global/paginator.html
{% if page_obj %}
  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page=1&q={{ request.GET.q.strip }}">&laquo; primeira</a>
      <a href="?page={{ page_obj.previous_page_number }}&q={{ request.GET.q.strip }}">anterior</a>
      {% endif %}
      
      <span class="current">
            Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
          </span>
          
          {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}&q={{ request.GET.q.strip }}">proximo</a>
          <a href="?page={{ page_obj.paginator.num_pages }}&q={{ request.GET.q.strip }}">ultima &raquo;</a>
          {% endif %}
    </span>
  </div>
{% endif %}